FROM rocky-openstack

# Data volume
VOLUME [ "/var/lib/nova" ]

# Service port
EXPOSE 8774

# Add scripts
COPY nova/startup.api.sh /startup.sh
COPY nova/healthy.api.sh /healthy.sh
COPY nova/config.sh config/openstack.env config/openstack.pw.env /
RUN chmod +x /healthy.sh /startup.sh /config.sh
RUN chmod 0600 /openstack.pw.env
RUN /config.sh
CMD ["/startup.sh"]
