FROM rocky-openstack

# Data volume
VOLUME [ "/var/lib/nova" ]

# Add scripts
COPY nova/startup.scheduler.sh /startup.sh
COPY nova/config.sh config/openstack.env config/openstack.pw.env /
RUN chmod +x /startup.sh /config.sh
RUN chmod 0600 /openstack.pw.env
RUN /config.sh
CMD ["/startup.sh"]
